import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SetStore } from './set-store'
import { Navbar } from '@/components/navbar/navbar'
import { ToastContainer } from 'react-toastify'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <SetStore>{children}</SetStore>
        </Providers>
      </body>
    </html>
  )
}
